:common:

:port:
  [
    tcp_21,
    tcp_22,
    tcp_23,
    #udp_53,
    tcp_80,
    tcp_111,
    #udp_123,
    #udp_161,
    #tcp_443,
    #tcp_445,
    #udp_636,
    #udp_1194,
    tcp_1433,
    tcp_3306,
    tcp_3389,
    tcp_5900,
    #tcp_8080,
    #tcp_49152,
  ]

:modules:
  [
    4000,
    4001,
  ]

:redis:
    :host: 127.0.0.1
    :port: 6379
    :password: 

:database:
    :adapter: mysql2
    :encoding: utf8
    :database: an
    :pool: 5
    :username: root
    :password:
    :host: localhost

